# Generated by Django 5.1 on 2024-08-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
        migrations.AddField(
            model_name='blog',
            name='html_content',
            field=models.FilePathField(blank=True, null=True, verbose_name='HTML Content Path'),
        ),
    ]
