# Generated by Django 5.1 on 2024-08-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_html_content_blog_html_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='html_file',
        ),
        migrations.AddField(
            model_name='blog',
            name='html_file_de',
            field=models.FileField(blank=True, null=True, upload_to='blog/templates/blog/entries/', verbose_name='HTML File German'),
        ),
        migrations.AddField(
            model_name='blog',
            name='html_file_en',
            field=models.FileField(blank=True, null=True, upload_to='blog/templates/blog/entries/', verbose_name='HTML File English'),
        ),
    ]
