# Generated by Django 5.1 on 2024-08-11 09:54

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_slug_remove_blog_title_blogtranslation'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='html_file_de',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='html_file_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='blog/templates/blog/entries/', verbose_name='HTML File'),
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
