# Generated by Django 5.1 on 2024-08-11 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_html_file_de_remove_blog_html_file_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
        ),
    ]
